// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEYp-Mm593iZvc8zoINJvpGlHjCZhM80',
    appId: '1:1025462695450:web:0d1eb00b07d9892db243a3',
    messagingSenderId: '1025462695450',
    projectId: 'postofficeapp-66b4a',
    authDomain: 'postofficeapp-66b4a.firebaseapp.com',
    databaseURL: 'https://postofficeapp-66b4a-default-rtdb.firebaseio.com',
    storageBucket: 'postofficeapp-66b4a.firebasestorage.app',
    measurementId: 'G-ESE8K4STM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGRkiObBSjf_8CihZU4W99oG4ldrQ2GM',
    appId: '1:1025462695450:android:62a9cb1fab244ffbb243a3',
    messagingSenderId: '1025462695450',
    projectId: 'postofficeapp-66b4a',
    databaseURL: 'https://postofficeapp-66b4a-default-rtdb.firebaseio.com',
    storageBucket: 'postofficeapp-66b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfbVqRS5MMIh5ZkT3Ti0ycLcDUtmKlvwQ',
    appId: '1:1025462695450:ios:79b7ec03311cb1e2b243a3',
    messagingSenderId: '1025462695450',
    projectId: 'postofficeapp-66b4a',
    databaseURL: 'https://postofficeapp-66b4a-default-rtdb.firebaseio.com',
    storageBucket: 'postofficeapp-66b4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrmViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfbVqRS5MMIh5ZkT3Ti0ycLcDUtmKlvwQ',
    appId: '1:1025462695450:ios:79b7ec03311cb1e2b243a3',
    messagingSenderId: '1025462695450',
    projectId: 'postofficeapp-66b4a',
    databaseURL: 'https://postofficeapp-66b4a-default-rtdb.firebaseio.com',
    storageBucket: 'postofficeapp-66b4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrmViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEYp-Mm593iZvc8zoINJvpGlHjCZhM80',
    appId: '1:1025462695450:web:74aad83026d853cab243a3',
    messagingSenderId: '1025462695450',
    projectId: 'postofficeapp-66b4a',
    authDomain: 'postofficeapp-66b4a.firebaseapp.com',
    databaseURL: 'https://postofficeapp-66b4a-default-rtdb.firebaseio.com',
    storageBucket: 'postofficeapp-66b4a.firebasestorage.app',
    measurementId: 'G-TY1V5E3M50',
  );
}
